---
- name: Restart the deployed Vega Robot Node
  hosts: all
  become: false
  vars_files:
    - defaults.yml
  tasks:
    - name: Stop the Vega process
      ansible.builtin.import_tasks: stop.yml
    - name: Start the Vega process
      ansible.builtin.import_tasks: start.yml
