---
- name: Start the deployed repository services
  ansible.builtin.command:
    argv: ["{{ dexcontrol_staging_dir }}/loop-service.sh", start]
  environment:
    LOOP_NODE_GRAPH_NODE_ENDPOINT: "{{ ansible_facts['env'].get('LOOP_NODE_GRAPH_NODE_ENDPOINT', '') }}"
  changed_when: true
